In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import datasets ## imports datasaets from skikit_learn
data = datasets.load_boston() ## loads Boston datasets from dataset library


In [4]:
print(data.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
print(data.feature_names)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [13]:
# define the data/predictors onthe preset feature names
X = pd.DataFrame(data.data,columns=data.feature_names)

#put the target (housing value --- MEDV) in another data fraame
y = data.target

In [14]:
X.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88

In [8]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

## Train Test Split

In [9]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

## Data Processing

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [19]:
# fir only to training data
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [20]:
# now apply the transform to data
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Training the Model

In [21]:
from sklearn import linear_model

In [22]:
model = linear_model.LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
predictions = model.predict(X_test)

In [24]:
predictions[:5]

array([14.45496003, 14.54295745,  9.34892027, 36.38563967, 24.44760923])

In [25]:
y_test[:5]

array([11. , 15.6,  8.3, 33.2, 22.8])

In [26]:
model.score(X_test,y_test)

0.6539976640837152

## Decision Tree Regressor

In [27]:
from sklearn.tree import DecisionTreeRegressor

In [28]:
DTR_model = DecisionTreeRegressor()
DTR_model.fit(X_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [29]:
predictions = DTR_model.predict(X_test)

In [30]:
predictions[:5]

array([12.8, 19.4, 10.8, 36.5, 25. ])

In [31]:
y_test[:5]

array([11. , 15.6,  8.3, 33.2, 22.8])

In [32]:
DTR_model.score(X_test,y_test)

0.818961940666172